project_id = "emolyyvmvvfjyxbguhyn"

[functions.send-app-link]
verify_jwt = false

[functions.ai-financial-advisor]
verify_jwt = true

[functions.sumsub-issue-token]
verify_jwt = true

[functions.payments-circle-webhook]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.log-security-event]
verify_jwt = false

[functions.vercel-auto-deploy]
verify_jwt = false

[functions.vercel-health]
verify_jwt = false

[functions.vercel-deployments]
verify_jwt = false

[functions.vercel-deploy]
verify_jwt = false

[functions.get-publishable-key]
verify_jwt = false